import { NextResponse } from "next/server";
import type { LiveUnderwritingDecision } from "@/lib/live-underwriting";

function generateLocalTemplate(decision: LiveUnderwritingDecision): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const formatCurrency = (val: number | null) => (val === null ? "TBD (Connect Bank to Verify)" : `$${Math.round(val).toLocaleString()}`);
  
  const isConditional = decision.status === "REQUEST INFO";
  
  if (isConditional) {
    return `# CONDITIONAL FACILITY OFFER & INFORMATION REQUEST
    
**Date:** ${date}
**Lender:** OceanX AI, Inc.
**Borrower:** ${decision.customerSummary.company}
**Status:** ⚠️ PENDING DATA VERIFICATION

## 1. INDICATIVE FACILITY STRUCTURE
OceanX AI has completed an initial automated review of your application. Based on current data, we have issued this **Conditional Offer**. Final facility limits and drawdown authorization are subject to the verification of the missing data points listed in Section 2.

*   **Indicative Total Facility Limit:** ${formatCurrency(decision.creditLimits.recommended.total)}
*   **Import Finance Sub-limit:** ${formatCurrency(decision.creditLimits.recommended.importFinance)}
*   **Inventory Finance Sub-limit:** ${formatCurrency(decision.creditLimits.recommended.inventoryFinance)}

## 2. MISSING DATA REQUIRED FOR INITIATION
To verify your limits and initiate the formal **Commercial Finance Facility Agreement**, the following actions are required:

${decision.mitigations.map((m) => `* **ACTION REQUIRED:** ${m}`).join("\n")}

## 3. INITIATION STEPS
1. **Connect Live Feeds:** Link your bank (for ADB verification) and accounting package (for revenue verification).
2. **Review:** Once connected, the Master Supervisor Agent will autonomously re-score the application.
3. **Execution:** Upon successful verification, a finalized execution-ready agreement will be generated for DocuSign signature.

---
*This document is an indicative offer generated by the OceanX AI Agentic Workflow and does not constitute a binding commitment until all conditions precedent are satisfied.*`;
  }

  return `# COMMERCIAL FINANCE FACILITY AGREEMENT

**Date:** ${date}
**Lender:** OceanX AI, Inc. (or Valkin Limited if UK jurisdiction)
**Borrower:** ${decision.customerSummary.company}
**Jurisdiction:** ${decision.customerSummary.country}

## 1. FACILITY AMOUNT & STRUCTURE
OceanX AI hereby agrees to provide a revolving credit facility to the Borrower under the following approved limits:
*   **Maximum Total Facility Limit:** ${formatCurrency(decision.creditLimits.recommended.total)}
*   **Import Finance Sub-limit:** ${formatCurrency(decision.creditLimits.recommended.importFinance)}
*   **Inventory Finance Sub-limit:** ${formatCurrency(decision.creditLimits.recommended.inventoryFinance)}

## 2. REPAYMENT TERMS
The Borrower agrees to repay the utilized facility via weekly direct debits via GoCardless. 
*   **Estimated Weekly Direct Debit:** ${formatCurrency(decision.repaymentFit.weeklyDebitEstimate)}
*   **Maximum Cycle Duration:** ${decision.repaymentFit.termWeeks} weeks per drawdown.

## 3. SECURITY & CONDITIONS
The Borrower acknowledges that Inventory Finance is secured against physical stock held in approved WMS facilities. 

**Special Conditions Precedent to Drawdown:**
${decision.mitigations.map((m) => `* ${m}`).join("\n")}

## 4. EXECUTION
This agreement is generated automatically by OceanX AI Contract Structuring Agent and is pending electronic signature via DocuSign.

**For OceanX AI:** _________________
**For ${decision.customerSummary.company}:** _________________`;
}

class MasterSupervisorAgent {
  static superviseHandoff(decision: LiveUnderwritingDecision) {
    const logs = [];
    let isApprovedForNextAgent = true;

    // 1. Check outputs for completeness
    if (decision.status === "AWAITING DATA") {
      logs.push("ERROR: Cannot route to Contract Agent. Awaiting source data.");
      isApprovedForNextAgent = false;
    }
    
    // 2. Flag critical errors / risk breaches
    if (decision.status === "REJECT") {
      logs.push("SUPERVISOR FLAG: Underwriting decision is REJECT. Halting pipeline.");
      isApprovedForNextAgent = false;
    }

    if (decision.status === "REQUEST INFO") {
      logs.push("SUPERVISOR ADVISORY: Missing critical data detected. Authorizing conditional contract generation with TBD placeholders for missing financial variables.");
      isApprovedForNextAgent = true;
    }

    // 3. Ensure mathematical integrity before legal drafting
    if (decision.creditLimits.recommended.total === null && decision.status === "APPROVE") {
      logs.push("CRITICAL ERROR: Underwriting approved but facility limit is null. Halting pipeline to prevent invalid contract.");
      isApprovedForNextAgent = false;
    }

    return { isApprovedForNextAgent, logs };
  }
}

export async function POST(request: Request) {
  try {
    const decision: LiveUnderwritingDecision = await request.json();

    // The Master Supervisor Agent oversees the handoff between Underwriting and Contract Agents
    const supervision = MasterSupervisorAgent.superviseHandoff(decision);
    
    if (!supervision.isApprovedForNextAgent) {
      return NextResponse.json({ 
        error: supervision.logs.join(" "), 
        supervisorLogs: supervision.logs 
      }, { status: 400 });
    }

    const key = process.env.GROQ_API_KEY;
    
    // If we have an API key, use the LLM to generate the contract to show true agentic behavior
    if (key) {
      const prompt = `You are Ocean AI's automated legal structuring agent. Your job is to draft a finalized, ready-to-sign Commercial Finance Agreement. 

Use this data from the Underwriting Agent:
Company Name: ${decision.customerSummary.company}
Country: ${decision.customerSummary.country}
Total Credit Limit: ${decision.creditLimits.recommended.total}
Import Finance Allocation: ${decision.creditLimits.recommended.importFinance}
Inventory Finance Allocation: ${decision.creditLimits.recommended.inventoryFinance}
Weekly Repayment Amount: ${decision.repaymentFit.weeklyDebitEstimate}
Repayment Term: ${decision.repaymentFit.termWeeks} weeks
Special Conditions: ${decision.mitigations.join(", ")}

Fill those variables into the following exact contract template and output ONLY the final document in Markdown.

---START TEMPLATE---
# COMMERCIAL FINANCE FACILITY AGREEMENT

**Date:** [Insert Current Date]
**Lender:** OceanX AI, Inc. (or Valkin Limited if UK jurisdiction)
**Borrower:** [Company Name]

## 1. FACILITY AMOUNT & STRUCTURE
OceanX AI hereby agrees to provide a revolving credit facility to the Borrower under the following approved limits:
*   **Maximum Total Facility Limit:** $[Total Credit Limit]
*   **Import Finance Sub-limit:** $[Import Finance Allocation]
*   **Inventory Finance Sub-limit:** $[Inventory Finance Allocation]

## 2. REPAYMENT TERMS
The Borrower agrees to repay the utilized facility via weekly direct debits via GoCardless. 
*   **Estimated Weekly Direct Debit:** $[Weekly Repayment Amount]
*   **Maximum Cycle Duration:** [Repayment Term] weeks per drawdown.

## 3. SECURITY & CONDITIONS
The Borrower acknowledges that Inventory Finance is secured against physical stock held in approved WMS facilities. 
**Special Conditions Precedent to Drawdown:**
[Insert Special Conditions here as bullet points. If none, write "Standard terms apply."]

## 4. EXECUTION
This agreement is generated automatically by OceanX AI Structuring Systems and is pending electronic signature via DocuSign.

**For OceanX AI:** _________________
**For [Company Name]:** _________________
---END TEMPLATE---`;

      try {
        const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${key}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            model: "llama-3.3-70b-versatile",
            temperature: 0,
            messages: [
              {
                role: "system",
                content: "You are a highly precise legal AI agent. Output exactly the requested Markdown template filled with the correct variables, with no conversational filler."
              },
              {
                role: "user",
                content: prompt
              }
            ]
          })
        });

        if (response.ok) {
          const data = await response.json();
          const content = data.choices?.[0]?.message?.content;
          if (content) {
            return NextResponse.json({ contract: content.replace(/---START TEMPLATE---|---END TEMPLATE---/g, "").trim(), generatedBy: "groq" });
          }
        }
      } catch (err) {
        console.error("LLM Generation failed, falling back to local", err);
      }
    }

    // Fallback if no GROQ key or API fails (guarantees the demo works flawlessly)
    const localContract = generateLocalTemplate(decision);
    return NextResponse.json({ contract: localContract, generatedBy: "template" });

  } catch (error) {
    return NextResponse.json({ error: "Failed to parse request data" }, { status: 400 });
  }
}
